### ISSUE TITLE
Migrator causes mismatch in MODS version info

### ISSUE THREAD

**Issue by jukervin** [Digital-Preservation-Finland/dpres-specification-migrator#1]
def fix_1_4_mets(root):
    """Migrates from catalog version 1.4 or 1.4.1 to newer by writing
    the following changes into the mets file:
    - adds the @MDTYPEVERSION attribute to all mets:mdWrap elements

Adding the MDTYPEVERSION doesn't check (and fix) possible version info from the metadata contained in xmlData.

In our case it changes MODS version to 3.6 in mets:mdWrap MDTYPEVERSION attribute but does not change (or remove it) from MODS:mods version attribute.

<mets:mdWrap MDTYPE="MODS" LABEL="Bibliographic meta-data of the digital version" MDTYPEVERSION="**3.6**">
	<mets:xmlData>
		<MODS:mods version="**3.4**">

**Comment by jmlehton** [comment]
This issue has been fixed and published in version v0.8.
